---
- name: Install NTP service in Hosts 
  hosts: all 
  become: yes 
  tasks:
    - name: Install NTP service in Centos 
      yum:
        name: "{{item}}" 
        state: present 
      when: ansible_distribution == "CentOS" 
      loop:
        - chrony
        - git
        - unzip
        - wget 

    - name: Install NTP service in Ubuntu 
      apt:
        name: "{{item}}"
        state: present 
        update_cache: yes 
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - git
        - unzip
        - wget

    - name: Start Service on Centos
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
      loop:
        - chronyd

    - name: Start NTP service on Ubuntu 
      service:
        name: "{{item}}" 
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"      
      loop:
        - ntp
